name: Needs More Info
description: Requests more info from newly opened issues/PRs that contain either default title/body or whose body is left blank
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication
    required: true
  CONFIG_FILE:
    description: Config file path relative to your repo's root.
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: alert-triangle
  color: green
